-- Identity & Access V1, step 3 of 3: tighten.
--
-- Generated by drizzle-kit, with two data conversions inserted by hand at the
-- only points where they are valid (marked HAND-WRITTEN). Each runs after the
-- constraint that would reject the old values is dropped and before the one
-- that would reject stale values is added.

ALTER TABLE "users" DROP CONSTRAINT "users_email_unique";--> statement-breakpoint
ALTER TABLE "users" DROP CONSTRAINT "users_status_valid";--> statement-breakpoint
-- HAND-WRITTEN: account states move to the V1 vocabulary. 'invited' had no
-- invitation mechanism behind it; it meant "created, not yet usable", which is
-- PENDING.
UPDATE "users" SET "status" = CASE "status"
  WHEN 'active' THEN 'ACTIVE'
  WHEN 'suspended' THEN 'SUSPENDED'
  ELSE 'PENDING'
END;--> statement-breakpoint
DROP INDEX "user_roles_user_id_idx";--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'PENDING';--> statement-breakpoint
-- HAND-WRITTEN: role codes move to the V1 catalogue. Parent, content manager,
-- support and auditor are not active roles in V1; no API ever existed to grant
-- them, so these deletes can only touch rows inserted by hand.
UPDATE "user_roles" SET "role" = CASE "role"
  WHEN 'owner' THEN 'OWNER'
  WHEN 'administrator' THEN 'ADMIN'
  WHEN 'supervisor' THEN 'SUPERVISOR'
  WHEN 'teacher' THEN 'TEACHER'
  WHEN 'assistant_teacher' THEN 'ASSISTANT_TEACHER'
  WHEN 'student' THEN 'STUDENT'
  ELSE "role"
END;--> statement-breakpoint
DELETE FROM "user_roles" WHERE "role" NOT IN (SELECT "code" FROM "roles");--> statement-breakpoint
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_role_roles_code_fk" FOREIGN KEY ("role") REFERENCES "public"."roles"("code") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "user_roles_role_idx" ON "user_roles" USING btree ("role");--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "email";--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_status_valid" CHECK ("users"."status" in ('PENDING', 'ACTIVE', 'SUSPENDED', 'DISABLED'));
