-- Messaging V1, step 1 of 2: schema (generated by drizzle-kit from the
-- modules' schema.ts files).
--
--   file_assets                files: stored-file metadata; the bytes live in
--                              the storage provider, never here
--   conversations              messaging: DIRECT / GROUP / CHANNEL, with the
--                              per-conversation sequence counter
--   conversation_participants  messaging: current and past membership, roles,
--                              read watermark, history window
--   messages                   messaging: server-ordered, idempotent per sender
--   message_attachments        messaging: references to file assets
--
-- Account and file ids are deliberately not foreign keys across modules.
-- See docs/architecture/messaging.md and storage.md.

CREATE TABLE "file_assets" (
	"id" text PRIMARY KEY NOT NULL,
	"owner_user_id" text NOT NULL,
	"kind" text NOT NULL,
	"content_type" text NOT NULL,
	"byte_size" bigint NOT NULL,
	"storage_key" text NOT NULL,
	"display_name" text NOT NULL,
	"status" text DEFAULT 'PENDING' NOT NULL,
	"duration_ms" integer,
	"width" integer,
	"height" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	CONSTRAINT "file_assets_storage_key_unique" UNIQUE("storage_key"),
	CONSTRAINT "file_assets_kind_valid" CHECK ("file_assets"."kind" in ('IMAGE', 'VOICE', 'AUDIO', 'DOCUMENT')),
	CONSTRAINT "file_assets_status_valid" CHECK ("file_assets"."status" in ('PENDING', 'AVAILABLE', 'REJECTED')),
	CONSTRAINT "file_assets_completion_consistent" CHECK (("file_assets"."status" = 'PENDING') = ("file_assets"."completed_at" is null)),
	CONSTRAINT "file_assets_size_positive" CHECK ("file_assets"."byte_size" > 0),
	CONSTRAINT "file_assets_content_type_shape" CHECK ("file_assets"."content_type" ~ '^[a-z]+/[a-z0-9.+-]+$'),
	CONSTRAINT "file_assets_display_name_present" CHECK (length("file_assets"."display_name") between 1 and 255),
	CONSTRAINT "file_assets_duration_valid" CHECK ("file_assets"."duration_ms" is null or ("file_assets"."duration_ms" > 0 and "file_assets"."kind" in ('VOICE', 'AUDIO'))),
	CONSTRAINT "file_assets_dimensions_valid" CHECK (("file_assets"."width" is null) = ("file_assets"."height" is null) and ("file_assets"."width" is null or ("file_assets"."width" > 0 and "file_assets"."height" > 0 and "file_assets"."kind" = 'IMAGE')))
);
--> statement-breakpoint
CREATE TABLE "conversation_participants" (
	"conversation_id" text NOT NULL,
	"user_id" text NOT NULL,
	"role" text NOT NULL,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL,
	"left_at" timestamp with time zone,
	"added_by" text,
	"last_read_sequence" bigint DEFAULT 0 NOT NULL,
	"hidden_through_sequence" bigint DEFAULT 0 NOT NULL,
	CONSTRAINT "conversation_participants_conversation_id_user_id_pk" PRIMARY KEY("conversation_id","user_id"),
	CONSTRAINT "conversation_participants_role_valid" CHECK ("conversation_participants"."role" in ('OWNER', 'PUBLISHER', 'MEMBER')),
	CONSTRAINT "conversation_participants_read_state_valid" CHECK ("conversation_participants"."hidden_through_sequence" >= 0 and "conversation_participants"."last_read_sequence" >= "conversation_participants"."hidden_through_sequence"),
	CONSTRAINT "conversation_participants_left_after_joined" CHECK ("conversation_participants"."left_at" is null or "conversation_participants"."left_at" >= "conversation_participants"."joined_at")
);
--> statement-breakpoint
CREATE TABLE "conversations" (
	"id" text PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"title" text,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"direct_user_low" text,
	"direct_user_high" text,
	"last_sequence" bigint DEFAULT 0 NOT NULL,
	"last_message_at" timestamp with time zone,
	"member_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "conversations_direct_pair_unique" UNIQUE("direct_user_low","direct_user_high"),
	CONSTRAINT "conversations_type_valid" CHECK ("conversations"."type" in ('DIRECT', 'GROUP', 'CHANNEL')),
	CONSTRAINT "conversations_direct_pair_shape" CHECK (("conversations"."direct_user_low" is null) = ("conversations"."direct_user_high" is null) and ("conversations"."type" = 'DIRECT') = ("conversations"."direct_user_low" is not null) and ("conversations"."direct_user_low" is null or "conversations"."direct_user_low" < "conversations"."direct_user_high")),
	CONSTRAINT "conversations_title_shape" CHECK (("conversations"."type" = 'DIRECT') = ("conversations"."title" is null) and ("conversations"."title" is null or char_length("conversations"."title") between 1 and 100)),
	CONSTRAINT "conversations_sequence_nonnegative" CHECK ("conversations"."last_sequence" >= 0),
	CONSTRAINT "conversations_member_count_nonnegative" CHECK ("conversations"."member_count" >= 0),
	CONSTRAINT "conversations_activity_consistent" CHECK (("conversations"."last_sequence" = 0) = ("conversations"."last_message_at" is null))
);
--> statement-breakpoint
CREATE TABLE "message_attachments" (
	"message_id" text NOT NULL,
	"position" integer NOT NULL,
	"file_asset_id" text NOT NULL,
	CONSTRAINT "message_attachments_message_id_position_pk" PRIMARY KEY("message_id","position"),
	CONSTRAINT "message_attachments_position_valid" CHECK ("message_attachments"."position" between 0 and 9)
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" text PRIMARY KEY NOT NULL,
	"conversation_id" text NOT NULL,
	"sequence" bigint NOT NULL,
	"sender_id" text NOT NULL,
	"type" text NOT NULL,
	"body" text,
	"reply_to_message_id" text,
	"client_message_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"edited_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "messages_conversation_sequence_unique" UNIQUE("conversation_id","sequence"),
	CONSTRAINT "messages_idempotency_unique" UNIQUE("conversation_id","sender_id","client_message_id"),
	CONSTRAINT "messages_type_valid" CHECK ("messages"."type" in ('TEXT', 'VOICE', 'IMAGE', 'FILE')),
	CONSTRAINT "messages_sequence_positive" CHECK ("messages"."sequence" > 0),
	CONSTRAINT "messages_body_length" CHECK ("messages"."body" is null or char_length("messages"."body") between 1 and 4000),
	CONSTRAINT "messages_text_has_body" CHECK ("messages"."type" <> 'TEXT' or "messages"."body" is not null or "messages"."deleted_at" is not null),
	CONSTRAINT "messages_client_message_id_shape" CHECK ("messages"."client_message_id" ~ '^[A-Za-z0-9_-]{8,64}$'),
	CONSTRAINT "messages_lifecycle_after_creation" CHECK (("messages"."edited_at" is null or "messages"."edited_at" >= "messages"."created_at") and ("messages"."deleted_at" is null or "messages"."deleted_at" >= "messages"."created_at"))
);
--> statement-breakpoint
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_attachments" ADD CONSTRAINT "message_attachments_message_id_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_reply_to_message_id_messages_id_fk" FOREIGN KEY ("reply_to_message_id") REFERENCES "public"."messages"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "file_assets_pending_idx" ON "file_assets" USING btree ("created_at") WHERE "file_assets"."status" = 'PENDING';--> statement-breakpoint
CREATE INDEX "conversation_participants_user_current_idx" ON "conversation_participants" USING btree ("user_id") WHERE "conversation_participants"."left_at" is null;