-- Notifications V1: schema (generated by drizzle-kit from the notifications
-- module's schema.ts).
--
--   notifications             one person's inbox: typed, localized by key,
--                             unread while read_at is null; one row per source
--                             fact and recipient (notifications_dedupe_unique)
--   notification_preferences  per person and category: in-app, realtime, push;
--                             no row means the defaults
--   notification_devices      app installations that receive push; one owner
--                             per (provider, token)
--
-- Account ids are deliberately not foreign keys across modules: suspending or
-- disabling an account leaves its notification history alone.
-- See docs/architecture/notifications.md.

CREATE TABLE "notification_devices" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"platform" text NOT NULL,
	"provider" text NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"last_seen_at" timestamp with time zone NOT NULL,
	"disabled_at" timestamp with time zone,
	CONSTRAINT "notification_devices_token_unique" UNIQUE("provider","token"),
	CONSTRAINT "notification_devices_platform_valid" CHECK ("notification_devices"."platform" in ('IOS', 'ANDROID', 'WEB')),
	CONSTRAINT "notification_devices_provider_valid" CHECK ("notification_devices"."provider" in ('APNS', 'FCM')),
	CONSTRAINT "notification_devices_apns_is_ios" CHECK ("notification_devices"."provider" <> 'APNS' or "notification_devices"."platform" = 'IOS'),
	CONSTRAINT "notification_devices_token_length" CHECK (char_length("notification_devices"."token") between 32 and 1024)
);
--> statement-breakpoint
CREATE TABLE "notification_preferences" (
	"user_id" text NOT NULL,
	"category" text NOT NULL,
	"in_app" boolean NOT NULL,
	"realtime" boolean NOT NULL,
	"push" boolean NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "notification_preferences_user_id_category_pk" PRIMARY KEY("user_id","category"),
	CONSTRAINT "notification_preferences_category_shape" CHECK ("notification_preferences"."category" ~ '^[A-Z][A-Z_]{0,31}$')
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" text PRIMARY KEY NOT NULL,
	"recipient_user_id" text NOT NULL,
	"type" text NOT NULL,
	"category" text NOT NULL,
	"title_key" text NOT NULL,
	"body_key" text NOT NULL,
	"params" jsonb NOT NULL,
	"target" jsonb NOT NULL,
	"dedupe_key" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"read_at" timestamp with time zone,
	CONSTRAINT "notifications_dedupe_unique" UNIQUE("recipient_user_id","dedupe_key"),
	CONSTRAINT "notifications_type_shape" CHECK ("notifications"."type" ~ '^[A-Z][A-Z_]{0,63}$'),
	CONSTRAINT "notifications_category_shape" CHECK ("notifications"."category" ~ '^[A-Z][A-Z_]{0,31}$'),
	CONSTRAINT "notifications_template_keys_shape" CHECK ("notifications"."title_key" ~ '^notification\.[a-z0-9_]{1,40}\.[a-z0-9_]{1,40}$' and "notifications"."body_key" ~ '^notification\.[a-z0-9_]{1,40}\.[a-z0-9_]{1,40}$'),
	CONSTRAINT "notifications_params_is_object" CHECK (jsonb_typeof("notifications"."params") = 'object'),
	CONSTRAINT "notifications_target_has_kind" CHECK (jsonb_typeof("notifications"."target") = 'object' and jsonb_typeof("notifications"."target" -> 'kind') = 'string'),
	CONSTRAINT "notifications_dedupe_key_length" CHECK (char_length("notifications"."dedupe_key") between 1 and 200),
	CONSTRAINT "notifications_read_after_created" CHECK ("notifications"."read_at" is null or "notifications"."read_at" >= "notifications"."created_at")
);
--> statement-breakpoint
CREATE INDEX "notification_devices_user_enabled_idx" ON "notification_devices" USING btree ("user_id","last_seen_at") WHERE "notification_devices"."disabled_at" is null;--> statement-breakpoint
CREATE INDEX "notifications_recipient_created_idx" ON "notifications" USING btree ("recipient_user_id","created_at","id");--> statement-breakpoint
CREATE INDEX "notifications_recipient_unread_idx" ON "notifications" USING btree ("recipient_user_id","created_at","id") WHERE "notifications"."read_at" is null;