-- Academic Core V1: schema (generated by drizzle-kit from the academic
-- module's schema.ts).
--
--   academic_sections              top-level educational areas (the profile's sections)
--   academic_programs              educational offerings, one section each
--   academic_halaqat               الحلقات: the groups students are enrolled in
--   academic_teacher_assignments   teacher <-> halaqa, contextual and dated; history kept
--   academic_enrollments           student <-> halaqa; ACTIVE until ended; history kept
--
-- Account ids are deliberately not foreign keys across modules; inside academic
-- the keys are RESTRICT, so nothing history refers to can be deleted under it.
-- The institution's structure is NOT seeded here: seeding is an explicit,
-- idempotent bootstrap step (docs/architecture/academic.md, "Seeding").

CREATE TABLE "academic_enrollments" (
	"id" text PRIMARY KEY NOT NULL,
	"student_user_id" text NOT NULL,
	"halaqa_id" text NOT NULL,
	"status" text NOT NULL,
	"enrolled_at" timestamp with time zone NOT NULL,
	"enrolled_by" text,
	"ended_at" timestamp with time zone,
	"ended_by" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "academic_enrollments_status_valid" CHECK ("academic_enrollments"."status" in ('ACTIVE', 'COMPLETED', 'WITHDRAWN')),
	CONSTRAINT "academic_enrollments_ended_consistent" CHECK (("academic_enrollments"."status" = 'ACTIVE') = ("academic_enrollments"."ended_at" is null)),
	CONSTRAINT "academic_enrollments_ended_after_enrolled" CHECK ("academic_enrollments"."ended_at" is null or "academic_enrollments"."ended_at" >= "academic_enrollments"."enrolled_at"),
	CONSTRAINT "academic_enrollments_updated_after_created" CHECK ("academic_enrollments"."updated_at" >= "academic_enrollments"."created_at")
);
--> statement-breakpoint
CREATE TABLE "academic_halaqat" (
	"id" text PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"program_id" text NOT NULL,
	"name" text NOT NULL,
	"sort_order" integer NOT NULL,
	"status" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "academic_halaqat_code_unique" UNIQUE("code"),
	CONSTRAINT "academic_halaqat_code_shape" CHECK ("academic_halaqat"."code" ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length("academic_halaqat"."code") between 2 and 64),
	CONSTRAINT "academic_halaqat_name_length" CHECK (char_length("academic_halaqat"."name") between 1 and 120),
	CONSTRAINT "academic_halaqat_status_valid" CHECK ("academic_halaqat"."status" in ('ACTIVE', 'INACTIVE')),
	CONSTRAINT "academic_halaqat_order_range" CHECK ("academic_halaqat"."sort_order" between 1 and 10000),
	CONSTRAINT "academic_halaqat_updated_after_created" CHECK ("academic_halaqat"."updated_at" >= "academic_halaqat"."created_at")
);
--> statement-breakpoint
CREATE TABLE "academic_programs" (
	"id" text PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"section_id" text NOT NULL,
	"name" text NOT NULL,
	"sort_order" integer NOT NULL,
	"description" text,
	"status" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "academic_programs_code_unique" UNIQUE("code"),
	CONSTRAINT "academic_programs_code_shape" CHECK ("academic_programs"."code" ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length("academic_programs"."code") between 2 and 64),
	CONSTRAINT "academic_programs_name_length" CHECK (char_length("academic_programs"."name") between 1 and 120),
	CONSTRAINT "academic_programs_description_length" CHECK ("academic_programs"."description" is null or char_length("academic_programs"."description") between 1 and 2000),
	CONSTRAINT "academic_programs_status_valid" CHECK ("academic_programs"."status" in ('ACTIVE', 'INACTIVE')),
	CONSTRAINT "academic_programs_order_range" CHECK ("academic_programs"."sort_order" between 1 and 10000),
	CONSTRAINT "academic_programs_updated_after_created" CHECK ("academic_programs"."updated_at" >= "academic_programs"."created_at")
);
--> statement-breakpoint
CREATE TABLE "academic_sections" (
	"id" text PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"kind" text NOT NULL,
	"sort_order" integer NOT NULL,
	"description" text,
	"status" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "academic_sections_code_unique" UNIQUE("code"),
	CONSTRAINT "academic_sections_code_shape" CHECK ("academic_sections"."code" ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length("academic_sections"."code") between 2 and 64),
	CONSTRAINT "academic_sections_name_length" CHECK (char_length("academic_sections"."name") between 1 and 120),
	CONSTRAINT "academic_sections_description_length" CHECK ("academic_sections"."description" is null or char_length("academic_sections"."description") between 1 and 2000),
	CONSTRAINT "academic_sections_kind_valid" CHECK ("academic_sections"."kind" in ('PROGRESSIVE', 'SPECIAL', 'ACCOMPANYING')),
	CONSTRAINT "academic_sections_status_valid" CHECK ("academic_sections"."status" in ('ACTIVE', 'INACTIVE')),
	CONSTRAINT "academic_sections_order_range" CHECK ("academic_sections"."sort_order" between 1 and 10000),
	CONSTRAINT "academic_sections_updated_after_created" CHECK ("academic_sections"."updated_at" >= "academic_sections"."created_at")
);
--> statement-breakpoint
CREATE TABLE "academic_teacher_assignments" (
	"id" text PRIMARY KEY NOT NULL,
	"halaqa_id" text NOT NULL,
	"teacher_user_id" text NOT NULL,
	"role" text NOT NULL,
	"status" text NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"assigned_by" text,
	"ended_at" timestamp with time zone,
	"ended_by" text,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "academic_teacher_assignments_role_valid" CHECK ("academic_teacher_assignments"."role" in ('TEACHER', 'ASSISTANT_TEACHER')),
	CONSTRAINT "academic_teacher_assignments_status_valid" CHECK ("academic_teacher_assignments"."status" in ('ACTIVE', 'ENDED')),
	CONSTRAINT "academic_teacher_assignments_ended_consistent" CHECK (("academic_teacher_assignments"."status" = 'ACTIVE') = ("academic_teacher_assignments"."ended_at" is null)),
	CONSTRAINT "academic_teacher_assignments_ended_after_started" CHECK ("academic_teacher_assignments"."ended_at" is null or "academic_teacher_assignments"."ended_at" >= "academic_teacher_assignments"."started_at")
);
--> statement-breakpoint
ALTER TABLE "academic_enrollments" ADD CONSTRAINT "academic_enrollments_halaqa_id_academic_halaqat_id_fk" FOREIGN KEY ("halaqa_id") REFERENCES "public"."academic_halaqat"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "academic_halaqat" ADD CONSTRAINT "academic_halaqat_program_id_academic_programs_id_fk" FOREIGN KEY ("program_id") REFERENCES "public"."academic_programs"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "academic_programs" ADD CONSTRAINT "academic_programs_section_id_academic_sections_id_fk" FOREIGN KEY ("section_id") REFERENCES "public"."academic_sections"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "academic_teacher_assignments" ADD CONSTRAINT "academic_teacher_assignments_halaqa_id_academic_halaqat_id_fk" FOREIGN KEY ("halaqa_id") REFERENCES "public"."academic_halaqat"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "academic_enrollments_active_unique" ON "academic_enrollments" USING btree ("student_user_id","halaqa_id") WHERE "academic_enrollments"."status" = 'ACTIVE';--> statement-breakpoint
CREATE INDEX "academic_enrollments_halaqa_idx" ON "academic_enrollments" USING btree ("halaqa_id","status","enrolled_at","id");--> statement-breakpoint
CREATE INDEX "academic_enrollments_student_idx" ON "academic_enrollments" USING btree ("student_user_id","enrolled_at","id");--> statement-breakpoint
CREATE INDEX "academic_halaqat_program_idx" ON "academic_halaqat" USING btree ("program_id","sort_order","code");--> statement-breakpoint
CREATE INDEX "academic_programs_section_idx" ON "academic_programs" USING btree ("section_id","sort_order","code");--> statement-breakpoint
CREATE UNIQUE INDEX "academic_teacher_assignments_active_unique" ON "academic_teacher_assignments" USING btree ("halaqa_id","teacher_user_id") WHERE "academic_teacher_assignments"."status" = 'ACTIVE';--> statement-breakpoint
CREATE INDEX "academic_teacher_assignments_halaqa_idx" ON "academic_teacher_assignments" USING btree ("halaqa_id","status","started_at","id");--> statement-breakpoint
CREATE INDEX "academic_teacher_assignments_teacher_idx" ON "academic_teacher_assignments" USING btree ("teacher_user_id","started_at","id");