-- Communities, step 2 of 2: schema (generated by drizzle-kit from the
-- communities module's schema.ts). Additive only: no existing table changes.
--
--   communities              the aggregate root: status, lifecycle and membership
--                            versions, and a maintained member count (no upper bound)
--   community_members        one row per stint — one stay of one account in one
--                            community; a rejoin is a new row, history is kept
--   community_invitations    links: only the SHA-256 of each token is stored,
--                            and the state is derived, never stored
--
-- Account ids are not foreign keys (accounts are identity's); inside the module
-- every key is RESTRICT, because a community is never deleted (Q47).

CREATE TABLE "communities" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"status" text NOT NULL,
	"lifecycle_version" integer DEFAULT 1 NOT NULL,
	"membership_version" bigint DEFAULT 0 NOT NULL,
	"member_count" integer DEFAULT 0 NOT NULL,
	"created_by" text,
	"created_at" timestamp with time zone NOT NULL,
	"status_changed_at" timestamp with time zone,
	"status_changed_by" text,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "communities_title_length" CHECK (char_length("communities"."title") between 1 and 100),
	CONSTRAINT "communities_status_valid" CHECK ("communities"."status" in ('OPEN', 'LOCKED')),
	CONSTRAINT "communities_lifecycle_version_positive" CHECK ("communities"."lifecycle_version" >= 1),
	CONSTRAINT "communities_membership_version_nonnegative" CHECK ("communities"."membership_version" >= 0),
	CONSTRAINT "communities_member_count_nonnegative" CHECK ("communities"."member_count" >= 0),
	CONSTRAINT "communities_updated_after_created" CHECK ("communities"."updated_at" >= "communities"."created_at")
);
--> statement-breakpoint
CREATE TABLE "community_invitations" (
	"id" text PRIMARY KEY NOT NULL,
	"community_id" text NOT NULL,
	"token_hash" text NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"max_uses" integer,
	"uses" integer DEFAULT 0 NOT NULL,
	"revoked_at" timestamp with time zone,
	"revoked_by" text,
	CONSTRAINT "community_invitations_token_hash_unique" UNIQUE("token_hash"),
	CONSTRAINT "community_invitations_token_hash_shape" CHECK ("community_invitations"."token_hash" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "community_invitations_expires_after_created" CHECK ("community_invitations"."expires_at" > "community_invitations"."created_at"),
	CONSTRAINT "community_invitations_max_uses_positive" CHECK ("community_invitations"."max_uses" is null or "community_invitations"."max_uses" >= 1),
	CONSTRAINT "community_invitations_uses_within_limit" CHECK ("community_invitations"."uses" >= 0 and ("community_invitations"."max_uses" is null or "community_invitations"."uses" <= "community_invitations"."max_uses")),
	CONSTRAINT "community_invitations_revoked_after_created" CHECK ("community_invitations"."revoked_at" is null or "community_invitations"."revoked_at" >= "community_invitations"."created_at")
);
--> statement-breakpoint
CREATE TABLE "community_members" (
	"id" text PRIMARY KEY NOT NULL,
	"community_id" text NOT NULL,
	"user_id" text NOT NULL,
	"status" text NOT NULL,
	"standing" text DEFAULT 'MEMBER' NOT NULL,
	"source" text NOT NULL,
	"added_by" text,
	"invitation_id" text,
	"joined_at" timestamp with time zone NOT NULL,
	"ended_at" timestamp with time zone,
	"ended_by" text,
	"version" bigint NOT NULL,
	CONSTRAINT "community_members_stint_key" UNIQUE("id","community_id","user_id"),
	CONSTRAINT "community_members_status_valid" CHECK ("community_members"."status" in ('ACTIVE', 'LEFT', 'REMOVED')),
	CONSTRAINT "community_members_standing_valid" CHECK ("community_members"."standing" in ('OWNER', 'MEMBER')),
	CONSTRAINT "community_members_source_valid" CHECK ("community_members"."source" in ('ADDED', 'INVITATION')),
	CONSTRAINT "community_members_version_positive" CHECK ("community_members"."version" > 0),
	CONSTRAINT "community_members_ended_consistent" CHECK (("community_members"."status" = 'ACTIVE') = ("community_members"."ended_at" is null)),
	CONSTRAINT "community_members_ended_after_joined" CHECK ("community_members"."ended_at" is null or "community_members"."ended_at" >= "community_members"."joined_at"),
	CONSTRAINT "community_members_source_consistent" CHECK (("community_members"."source" = 'INVITATION') = ("community_members"."invitation_id" is not null)),
	CONSTRAINT "community_members_owner_active" CHECK ("community_members"."standing" <> 'OWNER' or "community_members"."status" = 'ACTIVE'),
	CONSTRAINT "community_members_left_by_self" CHECK ("community_members"."status" <> 'LEFT' or "community_members"."ended_by" = "community_members"."user_id")
);
--> statement-breakpoint
ALTER TABLE "community_invitations" ADD CONSTRAINT "community_invitations_community_id_communities_id_fk" FOREIGN KEY ("community_id") REFERENCES "public"."communities"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "community_members" ADD CONSTRAINT "community_members_community_id_communities_id_fk" FOREIGN KEY ("community_id") REFERENCES "public"."communities"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "community_members" ADD CONSTRAINT "community_members_invitation_id_community_invitations_id_fk" FOREIGN KEY ("invitation_id") REFERENCES "public"."community_invitations"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "communities_created_idx" ON "communities" USING btree ("created_at","id");--> statement-breakpoint
CREATE INDEX "community_invitations_community_idx" ON "community_invitations" USING btree ("community_id","created_at","id");--> statement-breakpoint
CREATE UNIQUE INDEX "community_members_current_unique" ON "community_members" USING btree ("community_id","user_id") WHERE "community_members"."status" = 'ACTIVE';--> statement-breakpoint
CREATE UNIQUE INDEX "community_members_owner_unique" ON "community_members" USING btree ("community_id") WHERE "community_members"."standing" = 'OWNER';--> statement-breakpoint
CREATE UNIQUE INDEX "community_members_version_unique" ON "community_members" USING btree ("community_id","version");--> statement-breakpoint
CREATE INDEX "community_members_roster_idx" ON "community_members" USING btree ("community_id","joined_at","user_id") WHERE "community_members"."status" = 'ACTIVE';--> statement-breakpoint
CREATE INDEX "community_members_user_idx" ON "community_members" USING btree ("user_id","joined_at","community_id") WHERE "community_members"."status" = 'ACTIVE';--> statement-breakpoint
CREATE INDEX "community_members_history_idx" ON "community_members" USING btree ("community_id","user_id","version" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "community_members_invitation_idx" ON "community_members" USING btree ("invitation_id") WHERE "community_members"."invitation_id" is not null;