-- Communities, delegation (P3): capability grants (generated by drizzle-kit
-- from the communities module's schema.ts). Additive only: one new table, no
-- existing table or row changes.
--
--   communities_capability_grants   one capability given by a community's owner
--                                   to one member's stint; ended once — revoked,
--                                   with its stint, or when its holder becomes
--                                   owner — and never deleted; a re-grant is a
--                                   new row
--
-- The composite key (membership_id, community_id, user_id) must be the stint's
-- own triple (community_members_stint_key, from 0010), so a grant in one
-- community gives nothing in another and a rejoin never revives one. The
-- capability CHECK lists exactly COMMUNITY_CAPABILITIES; the two attendance
-- capabilities are added by a later CHECK migration (P9, held).

CREATE TABLE "communities_capability_grants" (
	"id" text PRIMARY KEY NOT NULL,
	"community_id" text NOT NULL,
	"membership_id" text NOT NULL,
	"user_id" text NOT NULL,
	"capability" text NOT NULL,
	"granted_by" text NOT NULL,
	"granted_at" timestamp with time zone NOT NULL,
	"ended_at" timestamp with time zone,
	"ended_by" text,
	"end_reason" text,
	CONSTRAINT "communities_capability_grants_capability_valid" CHECK ("communities_capability_grants"."capability" in ('community.members.view', 'community.members.invite', 'community.members.remove', 'community.lock', 'community.chat.post', 'community.live.start', 'community.live.moderate')),
	CONSTRAINT "communities_capability_grants_not_self" CHECK ("communities_capability_grants"."granted_by" <> "communities_capability_grants"."user_id"),
	CONSTRAINT "communities_capability_grants_ended_by_needs_end" CHECK ("communities_capability_grants"."ended_by" is null or "communities_capability_grants"."ended_at" is not null),
	CONSTRAINT "communities_capability_grants_ended_after_granted" CHECK ("communities_capability_grants"."ended_at" is null or "communities_capability_grants"."ended_at" >= "communities_capability_grants"."granted_at"),
	CONSTRAINT "communities_capability_grants_end_reason_valid" CHECK ("communities_capability_grants"."end_reason" in ('revoked', 'membership_ended', 'ownership_changed')),
	CONSTRAINT "communities_capability_grants_end_consistent" CHECK (("communities_capability_grants"."ended_at" is null) = ("communities_capability_grants"."end_reason" is null))
);
--> statement-breakpoint
ALTER TABLE "communities_capability_grants" ADD CONSTRAINT "communities_capability_grants_stint_fk" FOREIGN KEY ("membership_id","community_id","user_id") REFERENCES "public"."community_members"("id","community_id","user_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "communities_capability_grants_active_unique" ON "communities_capability_grants" USING btree ("membership_id","capability") WHERE "communities_capability_grants"."ended_at" is null;--> statement-breakpoint
CREATE INDEX "communities_capability_grants_active_by_community" ON "communities_capability_grants" USING btree ("community_id","capability","user_id") WHERE "communities_capability_grants"."ended_at" is null;--> statement-breakpoint
CREATE INDEX "communities_capability_grants_active_by_user" ON "communities_capability_grants" USING btree ("user_id","community_id") WHERE "communities_capability_grants"."ended_at" is null;