-- Community chat (P4): a community's chat is an ordinary messaging
-- conversation linked to the community (generated by drizzle-kit from the
-- messaging module's schema.ts; docs/architecture/community-chat.md §12.3).
-- Additive: new nullable columns, two indexes, two CHECKs. Every existing
-- row gets NULLs and keeps today's behaviour; no row is rewritten.
--
--   conversations.community_id                 the community whose chat this is;
--                                              plain text, no FK across modules
--   conversations.projected_membership_version the projection reflects every
--                                              membership change up to this version
--   conversation_participants.source_*         a projected row's provenance: the
--                                              authority's version, stint id, start
--   conversations_community_unique             one chat per community; decides
--                                              racing materializations
--   conversation_participants_current_idx      a conversation's current members, by
--                                              user id: member pages stay range
--                                              scans under churn (gate G2)
--
-- conversations_title_shape is replaced, not dropped: the new CHECK admits a
-- NULL title for a community chat (its title is Communities', read when
-- viewed) and is identical to the old one for every row whose community_id
-- is NULL — that is, every row that exists when this runs. The drop and the
-- re-add run in the migration's one transaction.

ALTER TABLE "conversations" DROP CONSTRAINT "conversations_title_shape";--> statement-breakpoint
ALTER TABLE "conversation_participants" ADD COLUMN "source_version" bigint;--> statement-breakpoint
ALTER TABLE "conversation_participants" ADD COLUMN "source_membership_id" text;--> statement-breakpoint
ALTER TABLE "conversation_participants" ADD COLUMN "source_joined_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "conversations" ADD COLUMN "community_id" text;--> statement-breakpoint
ALTER TABLE "conversations" ADD COLUMN "projected_membership_version" bigint;--> statement-breakpoint
CREATE INDEX "conversation_participants_current_idx" ON "conversation_participants" USING btree ("conversation_id","user_id") WHERE "conversation_participants"."left_at" is null;--> statement-breakpoint
CREATE UNIQUE INDEX "conversations_community_unique" ON "conversations" USING btree ("community_id") WHERE "conversations"."community_id" is not null;--> statement-breakpoint
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_source_shape" CHECK (("conversation_participants"."source_version" is null) = ("conversation_participants"."source_membership_id" is null) and ("conversation_participants"."source_version" is null) = ("conversation_participants"."source_joined_at" is null) and ("conversation_participants"."source_version" is null or "conversation_participants"."source_version" > 0) and ("conversation_participants"."source_version" is null or ("conversation_participants"."role" = 'MEMBER' and "conversation_participants"."added_by" is null)));--> statement-breakpoint
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_community_chat_shape" CHECK (("conversations"."community_id" is null) = ("conversations"."projected_membership_version" is null) and ("conversations"."community_id" is null or "conversations"."type" <> 'DIRECT') and ("conversations"."projected_membership_version" is null or "conversations"."projected_membership_version" >= 0));--> statement-breakpoint
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_title_shape" CHECK (("conversations"."type" = 'DIRECT' or "conversations"."community_id" is not null) = ("conversations"."title" is null) and ("conversations"."title" is null or char_length("conversations"."title") between 1 and 100));