-- Live (P6): community-scoped live sessions (generated by drizzle-kit from
-- the live module's schema.ts; docs/architecture/live.md §10.1, P6 audit §10).
-- Additive only: it creates Live's four tables with their CHECKs, keys and
-- indexes, and alters, drops or updates nothing that exists — no existing
-- table, column, constraint, index or row changes.
--
--   live_sessions             one live session of one community: the aggregate
--                             root, whose row is the lock for everything below;
--                             at most one live per community
--                             (live_sessions_one_live_per_community)
--   live_speaker_requests     the raise-hand queue: at most one open request per
--                             person and session; a raise after a closed one is
--                             a new row
--   live_presenter_grants     the screen-share slot: at most one open grant per
--                             session; a later claim is a new row
--   live_moderation_actions   every moderation act, written in the transaction
--                             that makes the change; a reason is a code, never
--                             free text
--
-- Community and account ids are plain text: no foreign key leaves Live's
-- tables, and none enters them. Inside Live every key is session_id →
-- live_sessions, RESTRICT: nothing is deleted (Q3). Every enumerated column's
-- CHECK lists exactly the domain's constant.
--
-- Forward-only, like every migration here (persistence.md): there is no down
-- step; dropping the four tables undoes it. Identity's seeded descriptions of
-- live.speak and live.moderate ("… in live sessions one hosts", 0002) are
-- deliberately NOT changed here: rewording catalogue text is not additive, and
-- is proposed separately as an identity-data migration (P6 audit §17.12).

CREATE TABLE "live_moderation_actions" (
	"id" text PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"actor_user_id" text,
	"target_user_id" text,
	"type" text NOT NULL,
	"at" timestamp with time zone NOT NULL,
	"reason_code" text,
	CONSTRAINT "live_moderation_actions_type_valid" CHECK ("live_moderation_actions"."type" in ('start_session', 'end_session', 'grant_speaker', 'decline_speaker', 'revoke_speaker', 'grant_presenter', 'revoke_presenter', 'reset_media', 'mute_participant', 'remove_participant')),
	CONSTRAINT "live_moderation_actions_reason_code_shape" CHECK ("live_moderation_actions"."reason_code" is null or "live_moderation_actions"."reason_code" ~ '^[a-z][a-z0-9_.]{0,63}$')
);
--> statement-breakpoint
CREATE TABLE "live_presenter_grants" (
	"id" text PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"user_id" text NOT NULL,
	"granted_by" text NOT NULL,
	"granted_at" timestamp with time zone NOT NULL,
	"ended_at" timestamp with time zone,
	"ended_by" text,
	"end_reason" text,
	CONSTRAINT "live_presenter_grants_end_reason_valid" CHECK ("live_presenter_grants"."end_reason" in ('stopped', 'revoked', 'session_ended', 'ineligible')),
	CONSTRAINT "live_presenter_grants_end_consistent" CHECK (("live_presenter_grants"."ended_at" is null) = ("live_presenter_grants"."end_reason" is null)),
	CONSTRAINT "live_presenter_grants_ended_by_needs_end" CHECK ("live_presenter_grants"."ended_by" is null or "live_presenter_grants"."ended_at" is not null)
);
--> statement-breakpoint
CREATE TABLE "live_sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"community_id" text NOT NULL,
	"host_user_id" text NOT NULL,
	"state" text NOT NULL,
	"state_version" bigint NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"ended_at" timestamp with time zone,
	"ended_by" text,
	"end_reason" text,
	"participant_cap" bigint NOT NULL,
	"moderator_reserve" bigint NOT NULL,
	"media_room_epoch" integer DEFAULT 0 NOT NULL,
	"empty_since" timestamp with time zone,
	"enforcement_violations" integer DEFAULT 0 NOT NULL,
	"last_violation_at" timestamp with time zone,
	CONSTRAINT "live_sessions_state_valid" CHECK ("live_sessions"."state" in ('live', 'ended')),
	CONSTRAINT "live_sessions_end_reason_valid" CHECK ("live_sessions"."end_reason" in ('moderator', 'idle', 'community_closed')),
	CONSTRAINT "live_sessions_state_version_positive" CHECK ("live_sessions"."state_version" >= 1),
	CONSTRAINT "live_sessions_participant_cap_positive" CHECK ("live_sessions"."participant_cap" > 0),
	CONSTRAINT "live_sessions_moderator_reserve_nonnegative" CHECK ("live_sessions"."moderator_reserve" >= 0),
	CONSTRAINT "live_sessions_media_room_epoch_nonnegative" CHECK ("live_sessions"."media_room_epoch" >= 0),
	CONSTRAINT "live_sessions_enforcement_violations_nonnegative" CHECK ("live_sessions"."enforcement_violations" >= 0),
	CONSTRAINT "live_sessions_ended_at_consistent" CHECK (("live_sessions"."state" = 'live') = ("live_sessions"."ended_at" is null)),
	CONSTRAINT "live_sessions_end_reason_consistent" CHECK (("live_sessions"."state" = 'live') = ("live_sessions"."end_reason" is null)),
	CONSTRAINT "live_sessions_moderator_end_named" CHECK ("live_sessions"."end_reason" is distinct from 'moderator' or "live_sessions"."ended_by" is not null),
	CONSTRAINT "live_sessions_ended_by_needs_end" CHECK ("live_sessions"."ended_by" is null or "live_sessions"."ended_at" is not null)
);
--> statement-breakpoint
CREATE TABLE "live_speaker_requests" (
	"id" text PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"user_id" text NOT NULL,
	"state" text NOT NULL,
	"requested_at" timestamp with time zone NOT NULL,
	"granted_at" timestamp with time zone,
	"decided_at" timestamp with time zone,
	"decided_by" text,
	CONSTRAINT "live_speaker_requests_state_valid" CHECK ("live_speaker_requests"."state" in ('pending', 'granted', 'declined', 'revoked', 'withdrawn', 'expired')),
	CONSTRAINT "live_speaker_requests_decided_at_consistent" CHECK (("live_speaker_requests"."state" = 'pending') = ("live_speaker_requests"."decided_at" is null)),
	CONSTRAINT "live_speaker_requests_decided_by_consistent" CHECK (("live_speaker_requests"."state" in ('pending', 'expired')) = ("live_speaker_requests"."decided_by" is null)),
	CONSTRAINT "live_speaker_requests_granted_at_set" CHECK ("live_speaker_requests"."state" <> 'granted' or "live_speaker_requests"."granted_at" is not null)
);
--> statement-breakpoint
ALTER TABLE "live_moderation_actions" ADD CONSTRAINT "live_moderation_actions_session_id_live_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."live_sessions"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "live_presenter_grants" ADD CONSTRAINT "live_presenter_grants_session_id_live_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."live_sessions"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "live_speaker_requests" ADD CONSTRAINT "live_speaker_requests_session_id_live_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."live_sessions"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "live_moderation_actions_session_idx" ON "live_moderation_actions" USING btree ("session_id","at","id");--> statement-breakpoint
CREATE UNIQUE INDEX "live_presenter_grants_one_open_per_session" ON "live_presenter_grants" USING btree ("session_id") WHERE "live_presenter_grants"."ended_at" is null;--> statement-breakpoint
CREATE INDEX "live_presenter_grants_closed_idx" ON "live_presenter_grants" USING btree ("session_id","ended_at");--> statement-breakpoint
CREATE UNIQUE INDEX "live_sessions_one_live_per_community" ON "live_sessions" USING btree ("community_id") WHERE "live_sessions"."state" = 'live';--> statement-breakpoint
CREATE INDEX "live_sessions_community_history_idx" ON "live_sessions" USING btree ("community_id","started_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX "live_sessions_live_page_idx" ON "live_sessions" USING btree ("started_at","id") WHERE "live_sessions"."state" = 'live';--> statement-breakpoint
CREATE UNIQUE INDEX "live_speaker_requests_one_open_per_person" ON "live_speaker_requests" USING btree ("session_id","user_id") WHERE "live_speaker_requests"."state" in ('pending', 'granted');--> statement-breakpoint
CREATE INDEX "live_speaker_requests_queue_idx" ON "live_speaker_requests" USING btree ("session_id","requested_at","id") WHERE "live_speaker_requests"."state" = 'pending';--> statement-breakpoint
CREATE INDEX "live_speaker_requests_granted_idx" ON "live_speaker_requests" USING btree ("session_id") WHERE "live_speaker_requests"."state" = 'granted';--> statement-breakpoint
CREATE INDEX "live_speaker_requests_floor_closed_idx" ON "live_speaker_requests" USING btree ("session_id","decided_at") WHERE "live_speaker_requests"."granted_at" is not null and "live_speaker_requests"."state" in ('revoked', 'withdrawn', 'expired');