import { createHmac, timingSafeEqual } from 'node:crypto';
import { mkdir, rm, stat } from 'node:fs/promises';
import { dirname, join, normalize, resolve, sep } from 'node:path';

import type { PresignedUpload, StorageProvider, UploadRequest } from '../domain/storage-provider';

/**
 * Filesystem-backed storage for development and single-node deployments.
 *
 * It implements the same signed-URL contract as an object store: the caller gets
 * a URL carrying an expiry and an HMAC, and only a request presenting a valid
 * signature may write that key. Keeping the contract identical is what lets the
 * S3 adapter drop in without any caller noticing.
 *
 * Note: the endpoint that *receives* these uploads is not part of this milestone
 * (see docs/architecture/storage.md, "Deferred"). Signing, verification and the
 * key/path safety rules below are complete and tested.
 */
export class LocalStorageProvider implements StorageProvider {
  private readonly root: string;

  constructor(
    root: string,
    private readonly signingSecret: string,
    private readonly baseUrl = '/files/local',
  ) {
    this.root = resolve(root);
  }

  async createUploadUrl(request: UploadRequest): Promise<PresignedUpload> {
    const expiresAt = Math.floor(Date.now() / 1000) + request.expiresInSeconds;
    const signature = this.sign(request.storageKey, expiresAt);

    return {
      url: `${this.baseUrl}/${encodeURI(request.storageKey)}?expires=${expiresAt}&signature=${signature}`,
      method: 'PUT',
      // Pinning the type here means a signed URL cannot be reused to upload
      // something of a different kind than the one we validated.
      headers: { 'content-type': request.contentType },
      storageKey: request.storageKey,
      expiresInSeconds: request.expiresInSeconds,
    };
  }

  async createDownloadUrl(storageKey: string, expiresInSeconds: number): Promise<string> {
    const expiresAt = Math.floor(Date.now() / 1000) + expiresInSeconds;
    const signature = this.sign(storageKey, expiresAt);
    return `${this.baseUrl}/${encodeURI(storageKey)}?expires=${expiresAt}&signature=${signature}`;
  }

  async exists(storageKey: string): Promise<boolean> {
    try {
      const stats = await stat(this.absolutePathFor(storageKey));
      return stats.isFile();
    } catch {
      return false;
    }
  }

  async delete(storageKey: string): Promise<void> {
    await rm(this.absolutePathFor(storageKey), { force: true });
  }

  /** Creates the parent directory for a key. Used by the receiving endpoint. */
  async ensureDirectoryFor(storageKey: string): Promise<string> {
    const absolute = this.absolutePathFor(storageKey);
    await mkdir(dirname(absolute), { recursive: true });
    return absolute;
  }

  /** Constant-time verification of a signed URL. */
  verify(storageKey: string, expiresAt: number, signature: string): boolean {
    if (!Number.isFinite(expiresAt) || expiresAt < Math.floor(Date.now() / 1000)) return false;

    const expected = Buffer.from(this.sign(storageKey, expiresAt));
    const provided = Buffer.from(signature);
    if (expected.length !== provided.length) return false;
    return timingSafeEqual(expected, provided);
  }

  private sign(storageKey: string, expiresAt: number): string {
    return createHmac('sha256', this.signingSecret)
      .update(`${storageKey}:${expiresAt}`)
      .digest('hex');
  }

  /**
   * Resolves a key inside the storage root, refusing anything that escapes it.
   * Keys are generated by us, but this is the last line of defence and costs
   * nothing.
   */
  private absolutePathFor(storageKey: string): string {
    const candidate = resolve(join(this.root, normalize(storageKey)));
    if (candidate !== this.root && !candidate.startsWith(this.root + sep)) {
      throw new Error('Storage key escapes the storage root.');
    }
    return candidate;
  }
}
