import { LocalStorageProvider } from './local-storage-provider';

describe('LocalStorageProvider', () => {
  const provider = new LocalStorageProvider('/tmp/institution-storage-test', 'test-secret');

  it('issues an upload URL pinned to the key and content type', async () => {
    const upload = await provider.createUploadUrl({
      storageKey: 'image/2026/01/asset-1',
      contentType: 'image/png',
      byteSize: 100,
      expiresInSeconds: 300,
    });

    expect(upload.method).toBe('PUT');
    expect(upload.headers['content-type']).toBe('image/png');
    expect(upload.url).toContain('image/2026/01/asset-1');
    expect(upload.url).toMatch(/signature=[a-f0-9]{64}/);
  });

  it('accepts a signature it produced', async () => {
    const url = await provider.createDownloadUrl('image/2026/01/asset-1', 300);
    const parsed = new URL(url, 'http://local');
    const expires = Number(parsed.searchParams.get('expires'));
    const signature = parsed.searchParams.get('signature') as string;

    expect(provider.verify('image/2026/01/asset-1', expires, signature)).toBe(true);
  });

  // Without this, a signed URL for one file would authorise reading any file.
  it('rejects a signature reused for a different key', async () => {
    const url = await provider.createDownloadUrl('image/2026/01/asset-1', 300);
    const parsed = new URL(url, 'http://local');
    const expires = Number(parsed.searchParams.get('expires'));
    const signature = parsed.searchParams.get('signature') as string;

    expect(provider.verify('image/2026/01/asset-OTHER', expires, signature)).toBe(false);
  });

  it('rejects an expired signature', () => {
    const past = Math.floor(Date.now() / 1000) - 10;
    const provider2 = new LocalStorageProvider('/tmp/institution-storage-test', 'test-secret');
    // Sign for a past expiry by verifying whatever signature: expiry is checked first.
    expect(provider2.verify('k', past, 'a'.repeat(64))).toBe(false);
  });

  it('rejects a tampered signature of the right length', async () => {
    const url = await provider.createDownloadUrl('k', 300);
    const expires = Number(new URL(url, 'http://local').searchParams.get('expires'));
    expect(provider.verify('k', expires, 'b'.repeat(64))).toBe(false);
  });

  // Keys are generated by us, but path traversal must still be impossible.
  it('refuses a key that escapes the storage root', async () => {
    await expect(provider.exists('../../etc/passwd')).resolves.toBe(false);
    await expect(provider.delete('../../../etc/passwd')).rejects.toThrow(/escapes/);
  });
});
