/**
 * P8 load harness — the deterministic scenario catalog. These are DEFINITIONS
 * only; nothing here runs. Numbers follow the ladder in docs/p8-load-capacity-
 * plan.md §8 and are starting points, overridable per run with flags. Each
 * scenario names its own stop conditions (which §9 signals end the run) and the
 * metric groups the collector should capture.
 *
 * Pure data + lookup; no SDK, no I/O.
 */
import { type Scenario } from '../core/config';

const HOST = 'host(cpu,softirq,mem,net-tx,udp-drops,softnet,conntrack)';
const LK = 'livekit(participants,tracks,loss,bitrate,connect-success)';
const API = 'api(rps,latency,errors,ws-connections)';
const DATA = 'data(redis-ops,pg-connections)';

/** Shared stop conditions, referenced by id into docs/p8-load-capacity-plan.md §9. */
const STOP_MEDIA: readonly string[] = [
  'hottest-core soft+sys > 85%',
  'UDP RcvbufErrors/InErrors rising',
  'softnet dropped rising',
  'livekit loss > 2%',
  'outbound > 700 Mbps',
  'MemAvailable < 8 GiB',
  'livekit health 406 or restart',
];
const STOP_API: readonly string[] = [
  '/health/ready p99 > 1s or non-200 > 1%',
  'pg connections > 90/100',
  'redis rejected_connections > 0',
  'nginx worker_connections exhaustion',
  'MemAvailable < 8 GiB',
];

export const SCENARIOS: readonly Scenario[] = [
  {
    id: 'api-baseline',
    title: '1. API baseline — control + realtime, no media',
    target: 'api',
    rooms: 0,
    listenersPerRoom: 0,
    speakersPerRoom: 0,
    screenSharesPerRoom: 0,
    relay: false,
    rampPerSecond: 20,
    holdSeconds: 300,
    apiConnections: 200,
    apiRequestsPerSecond: 50,
    expectedTraffic: 'light: ~50 RPS HTTP + 200 /realtime WS, small frames',
    stopConditions: STOP_API,
    metrics: [HOST, API, DATA],
    notes: 'Establishes the API/PG/Redis/nginx-HTTP floor before any media.',
  },
  {
    id: 'lk-listeners-10',
    title: '2. LiveKit 10 listeners (1 room, 1 speaker)',
    target: 'livekit',
    rooms: 1,
    listenersPerRoom: 10,
    speakersPerRoom: 1,
    screenSharesPerRoom: 0,
    relay: false,
    rampPerSecond: 5,
    holdSeconds: 120,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'audio only: ~10 × 40 kbps ≈ 0.4 Mbps outbound',
    stopConditions: STOP_MEDIA,
    metrics: [HOST, LK],
    notes: 'Harness correctness + per-listener cost baseline.',
  },
  {
    id: 'lk-listeners-100',
    title: '3. LiveKit 100 listeners (1 room, 1 speaker)',
    target: 'livekit',
    rooms: 1,
    listenersPerRoom: 100,
    speakersPerRoom: 1,
    screenSharesPerRoom: 0,
    relay: false,
    rampPerSecond: 20,
    holdSeconds: 300,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'audio only: ~100 × 40 kbps ≈ 4 Mbps outbound',
    stopConditions: STOP_MEDIA,
    metrics: [HOST, LK],
    notes: 'Linear-cost assumption check.',
  },
  {
    id: 'lk-listeners-500',
    title: '4. LiveKit 500 listeners (1 room, 1 speaker)',
    target: 'livekit',
    rooms: 1,
    listenersPerRoom: 500,
    speakersPerRoom: 1,
    screenSharesPerRoom: 0,
    relay: false,
    rampPerSecond: 50,
    holdSeconds: 600,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'audio only: ~500 × 40 kbps ≈ 20 Mbps outbound',
    stopConditions: STOP_MEDIA,
    metrics: [HOST, LK],
    notes: 'Watch softirq core % and PPS onset.',
  },
  {
    id: 'lk-listeners-1000',
    title: '5. LiveKit 1,000 listeners (1 room, 1 speaker)',
    target: 'livekit',
    rooms: 1,
    listenersPerRoom: 1_000,
    speakersPerRoom: 1,
    screenSharesPerRoom: 0,
    relay: false,
    rampPerSecond: 50,
    holdSeconds: 600,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'audio only: ~1,000 × 40 kbps ≈ 40 Mbps outbound',
    stopConditions: STOP_MEDIA,
    metrics: [HOST, LK],
    notes: 'Packet-loss onset watch.',
  },
  {
    id: 'lk-listeners-2000',
    title: '6. LiveKit 2,000 listeners (1 room, 1 speaker)',
    target: 'livekit',
    rooms: 1,
    listenersPerRoom: 2_000,
    speakersPerRoom: 1,
    screenSharesPerRoom: 0,
    relay: false,
    rampPerSecond: 75,
    holdSeconds: 600,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'audio only: ~2,000 × 40 kbps ≈ 80 Mbps outbound',
    stopConditions: STOP_MEDIA,
    metrics: [HOST, LK],
    notes: 'Approaching the single-NIC-queue limit.',
  },
  {
    id: 'lk-listeners-3000',
    title: '7. LiveKit 3,000 listeners (1 room, 1 speaker) — TARGET',
    target: 'livekit',
    rooms: 1,
    listenersPerRoom: 3_000,
    speakersPerRoom: 1,
    screenSharesPerRoom: 0,
    relay: false,
    rampPerSecond: 100,
    holdSeconds: 600,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'audio only: ~3,000 × 40 kbps ≈ 120 Mbps outbound',
    stopConditions: STOP_MEDIA,
    metrics: [HOST, LK],
    notes: 'Prove/disprove one-room 3k listeners. SFU-direct (bypasses the 300 app cap).',
  },
  {
    id: 'lk-multiroom-audio',
    title: '8. Multi-room audio (20 rooms × 500 listeners = 10,000) — TOTAL TARGET',
    target: 'livekit',
    rooms: 20,
    listenersPerRoom: 500,
    speakersPerRoom: 1,
    screenSharesPerRoom: 0,
    relay: false,
    rampPerSecond: 150,
    holdSeconds: 600,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'audio only: ~10,000 × 40 kbps ≈ 400 Mbps outbound',
    stopConditions: STOP_MEDIA,
    metrics: [HOST, LK],
    notes: 'Total-participant target; multi-room bookkeeping vs. one big room.',
  },
  {
    id: 'lk-speakers-4',
    title: '9. Multiple speakers (1 room, 4 speakers + 500 listeners)',
    target: 'livekit',
    rooms: 1,
    listenersPerRoom: 500,
    speakersPerRoom: 4,
    screenSharesPerRoom: 0,
    relay: false,
    rampPerSecond: 50,
    holdSeconds: 600,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'audio: up to 4 × 500 × 40 kbps ≈ 80 Mbps downstream fan-out',
    stopConditions: STOP_MEDIA,
    metrics: [HOST, LK],
    notes: 'Forwarder fan-in/out cost with several active publishers.',
  },
  {
    id: 'lk-screenshare',
    title: '10. Screen share (1 room, 1 screen publisher + 100 listeners)',
    target: 'livekit',
    rooms: 1,
    listenersPerRoom: 100,
    speakersPerRoom: 1,
    screenSharesPerRoom: 1,
    relay: false,
    rampPerSecond: 20,
    holdSeconds: 300,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'video ~1–2.5 Mbps × 100 ≈ 100–250 Mbps — expect saturation to arrive early',
    stopConditions: STOP_MEDIA,
    metrics: [HOST, LK],
    notes:
      'Find the screen-share saturation point (low hundreds), not the target. Uses the SCREEN_720P profile (P8.2); confirm achieved bitrate by measurement.',
    screenProfile: 'SCREEN_720P',
  },
  {
    id: 'lk-relay-500',
    title: '11. TURN relay (1 room, 500 listeners, relay forced) — capped by ~590 relay ports',
    target: 'livekit',
    rooms: 1,
    listenersPerRoom: 500,
    speakersPerRoom: 1,
    screenSharesPerRoom: 0,
    relay: true,
    rampPerSecond: 25,
    holdSeconds: 300,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'audio via TURN; ≤ ~590 relay ports (F2) — stay under the ceiling',
    stopConditions: [...STOP_MEDIA, 'relay allocation failures near ~590'],
    metrics: [HOST, LK],
    notes:
      'iceTransportType=TRANSPORT_RELAY (rtc-node). Measures relay + nginx TLS (5349) overhead.',
  },
  {
    id: 'lk-churn',
    title: '12. Reconnect / churn (1 room, 1,000 listeners, drop+re-add 30%)',
    target: 'livekit',
    rooms: 1,
    listenersPerRoom: 1_000,
    speakersPerRoom: 1,
    screenSharesPerRoom: 0,
    relay: false,
    rampPerSecond: 50,
    holdSeconds: 600,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'audio ~40 Mbps baseline + re-signalling spikes on each cycle',
    stopConditions: [...STOP_MEDIA, 'nginx accept/ws errors on reconnect spike'],
    metrics: [HOST, LK],
    notes: 'Reconnect storm: watch netdev_max_backlog (softnet drops) and signalling churn.',
    churn: { dropFraction: 0.3, cycleSeconds: 60, cycles: 5 },
  },
  {
    id: 'combined',
    title: '13. Combined API + LiveKit (10 rooms × 300 listeners + API load)',
    target: 'combined',
    rooms: 10,
    listenersPerRoom: 300,
    speakersPerRoom: 1,
    screenSharesPerRoom: 0,
    relay: false,
    rampPerSecond: 100,
    holdSeconds: 600,
    apiConnections: 1_000,
    apiRequestsPerSecond: 100,
    expectedTraffic: 'media ~3,000 × 40 kbps ≈ 120 Mbps + API HTTP/WS through the same nginx/cores',
    stopConditions: [...STOP_MEDIA, ...STOP_API],
    metrics: [HOST, LK, API, DATA],
    notes:
      'Last: cross-tier contention through the full nginx→api→livekit path at realistic ratios.',
  },
];

/**
 * Tiny OFF-BOX SMOKE scenarios (P8.2): 2 participants, 1 room, seconds long.
 * These are connectivity/path validation — NOT capacity tests. Kept separate
 * from the capacity ladder so the two can never be confused.
 */
export const SMOKE_SCENARIOS: readonly Scenario[] = [
  {
    id: 'smoke-audio',
    title: 'Smoke: audio (1 room, 1 speaker + 1 listener)',
    target: 'livekit',
    rooms: 1,
    listenersPerRoom: 1,
    speakersPerRoom: 1,
    screenSharesPerRoom: 0,
    relay: false,
    rampPerSecond: 2,
    holdSeconds: 12,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'one 440 Hz audio track, one subscriber — negligible',
    stopConditions: ['connect/publish failure'],
    metrics: [LK],
    notes: 'Path validation only. 2 participants max.',
  },
  {
    id: 'smoke-screen',
    title: 'Smoke: screen share (1 room, 1 screen publisher + 1 listener)',
    target: 'livekit',
    rooms: 1,
    listenersPerRoom: 1,
    speakersPerRoom: 0,
    screenSharesPerRoom: 1,
    relay: false,
    rampPerSecond: 2,
    holdSeconds: 15,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'one SCREEN_360P video track (~0.6 Mbps ceiling), one subscriber',
    stopConditions: ['connect/publish failure'],
    metrics: [LK],
    notes: 'Path validation + measure achieved screen bitrate. 2 participants max.',
    screenProfile: 'SCREEN_360P',
  },
  {
    id: 'smoke-relay',
    title: 'Smoke: forced TURN relay (1 room, 1 speaker + 1 listener)',
    target: 'livekit',
    rooms: 1,
    listenersPerRoom: 1,
    speakersPerRoom: 1,
    screenSharesPerRoom: 0,
    relay: true,
    rampPerSecond: 2,
    holdSeconds: 12,
    apiConnections: 0,
    apiRequestsPerSecond: 0,
    expectedTraffic: 'one audio track over forced TURN relay, one subscriber',
    stopConditions: ['connect failure (relay path unreachable)'],
    metrics: [LK],
    notes: 'Validates the TURN relay path externally. 2 participants max.',
  },
];

/** The capacity ladder (13) plus the smoke scenarios. */
export const ALL_SCENARIOS: readonly Scenario[] = [...SCENARIOS, ...SMOKE_SCENARIOS];

const BY_ID = new Map(ALL_SCENARIOS.map((s) => [s.id, s]));

export function getScenario(id: string): Scenario | undefined {
  return BY_ID.get(id);
}

export function scenarioIds(): string[] {
  return ALL_SCENARIOS.map((s) => s.id);
}
