name: quran_institution_app
description: "Visual prototype (UI only) for the Global Institution for Teaching the Noble Quran."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.2.0
  flutter_riverpod: ^3.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800
    - family: PlexArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf
          weight: 400
