import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsIn,
  IsInt,
  IsOptional,
  IsString,
  Max,
  MaxLength,
  Min,
} from 'class-validator';

/**
 * Transport shapes for /messaging. They bound what a request may carry; the
 * domain decides what is valid and answers with precise codes
 * (messaging.body_too_long, messaging.client_message_id_invalid, …). Unknown
 * fields are rejected outright (see configureApp).
 *
 * The array caps here mirror MAX_PARTICIPANTS_PER_REQUEST; the string caps are
 * abuse bounds, set well above the domain's own limits.
 */

const ID_MAX = 128;
const TEXT_MAX = 20_000;
const PER_REQUEST = 200;

export class StartDirectDto {
  @IsString()
  @MaxLength(ID_MAX)
  userId!: string;
}

export class CreateGroupDto {
  @IsString()
  @MaxLength(400)
  title!: string;

  @IsArray()
  @ArrayMaxSize(PER_REQUEST)
  @IsString({ each: true })
  @MaxLength(ID_MAX, { each: true })
  memberIds!: string[];
}

export class CreateChannelDto {
  @IsString()
  @MaxLength(400)
  title!: string;

  @IsOptional()
  @IsArray()
  @ArrayMaxSize(PER_REQUEST)
  @IsString({ each: true })
  @MaxLength(ID_MAX, { each: true })
  memberIds?: string[];

  @IsOptional()
  @IsArray()
  @ArrayMaxSize(PER_REQUEST)
  @IsString({ each: true })
  @MaxLength(ID_MAX, { each: true })
  publisherIds?: string[];
}

class SendBaseDto {
  /** Generated by the client (a UUID is ideal) and resent verbatim on every retry. */
  @IsString()
  @MaxLength(ID_MAX)
  clientMessageId!: string;

  @IsOptional()
  @IsString()
  @MaxLength(ID_MAX)
  replyToMessageId?: string | null;
}

export class SendTextDto extends SendBaseDto {
  @IsString()
  @MaxLength(TEXT_MAX)
  body!: string;
}

export class SendMediaDto extends SendBaseDto {
  /** A completed upload of the sender's own (POST /files/uploads, then …/complete). */
  @IsString()
  @MaxLength(ID_MAX)
  fileAssetId!: string;

  @IsOptional()
  @IsString()
  @MaxLength(TEXT_MAX)
  caption?: string | null;
}

export class MarkReadDto {
  /** The sequence of the newest message the reader has seen. */
  @IsInt()
  @Min(0)
  sequence!: number;
}

export class AddParticipantsDto {
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(PER_REQUEST)
  @IsString({ each: true })
  @MaxLength(ID_MAX, { each: true })
  userIds!: string[];

  /** Channels only: PUBLISHER may post. Default MEMBER. */
  @IsOptional()
  @IsIn(['MEMBER', 'PUBLISHER'])
  role?: 'MEMBER' | 'PUBLISHER';
}

export class ListConversationsQuery {
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(100)
  limit?: number;

  @IsOptional()
  @IsString()
  @MaxLength(512)
  cursor?: string;
}

export class ListMessagesQuery {
  /** Messages older than this sequence. */
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  before?: number;

  /** Messages newer than this sequence. */
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  after?: number;

  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(100)
  limit?: number;
}

export class ListParticipantsQuery {
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(500)
  limit?: number;

  @IsOptional()
  @IsString()
  @MaxLength(512)
  cursor?: string;
}
